name: Stata

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: get Stata
      run: |
        cd ~
        git clone https://github.com/luckykong/ActionTest.git
        cd ActionTest/stata-installer
        cat xa* > stata.tar.gz
        tar -xzf stata.tar.gz stata
    - name: install Stata
      run: |
        cd ~/ActionTest/stata-installer/stata
        ls -alh  
        ./install
        cp ~/ActionTest/stata-installer/stata.lic ./stata.lic
    - name: Run Stata
      run: stata-mp -e ~/ActionTest/dofiles/test.do
