name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: get Stata
      run: |
        curl -u tera_aimaomao:tera_aimaomao https://kita.teracloud.jp:443/dav/Stata/stata_moditified.tar.gz -o stata.tar.gz
        tar -xzf stata.tar.gz stata
        cd stata
        pwd
        ls
        
      
